version: "3"
services:
  nginx:
    image: nginx
    ports:
      - 80:80
    labels:
      - "Faculdade=Impacta"
      - "Turma=FS"
      - "maintener=Lucas <lucas.hayashi@faculdade>"
    container_name: nginx-impacta

  mysql:
    image: mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=123456
    ports:
      - 3306:3306
    labels:
      - "Faculdade=Impacta"
      - "Turma=FS"
      - "maintener=Lucas <lucas.hayashi@faculdade>"
    container_name: mysql-impacta
